Mundo_Tecnologico/Controllers/MarcasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Configuration;
using System.Data.SqlClient;
using Mundo_Tecnologico.Models;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;
using CrystalDecisions.Shared;

namespace Mundo_Tecnologico.Controllers
{
    public class MarcasController : Controller
    {

        string cadena = ConfigurationManager.ConnectionStrings["con"].ConnectionString;

        IEnumerable<Marca> ListarMarcas()
        {
            List<Marca> lista = new List<Marca>();

            using (SqlConnection con = new SqlConnection(cadena))
            {
                SqlCommand cmd = new SqlCommand("sp_listar_marcas", con);
                cmd.CommandType = CommandType.StoredProcedure;
                con.Open();

                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    Marca reg = new Marca()
                    {
                        codigo = dr.GetString(0),
                        nombre = dr.GetString(1),
                        estado = dr.GetByte(2)
                    };

                    lista.Add(reg);
                }

                dr.Close();
                con.Close();

            }

            return lista;
        }

        Marca BuscarMarca(string codigo)
        {
            if (codigo != null)
            {
                return ListarMarcas().Where(m => m.codigo == codigo).FirstOrDefault();
            }
            else
            {
                return null;
            }

        }

        string EditarMarca(Marca mar)
        {
            string mensaje = "";

            using (SqlConnection con = new SqlConnection(cadena))
            {
                try
                {
                    SqlCommand cmd = new SqlCommand("sp_editar_marca", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@cod", mar.codigo);
                    cmd.Parameters.AddWithValue("@nom", mar.nombre);
                    cmd.Parameters.AddWithValue("@estado", mar.estado);

                    con.Open();
                    cmd.ExecuteNonQuery();
                    mensaje = "Marca editada con exito";
                }
                catch (Exception ex)
                {
                    mensaje = ex.Message;
                }
                finally
                {
                    con.Close();
                }

            }

            return mensaje;
        }

        string RegistrarMarca(Marca mar)
        {
            string mensaje = "";
            using (SqlConnection con = new SqlConnection(cadena))
            {
                try
                {
                    SqlCommand cmd = new SqlCommand("sp_registrar_marca", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@nom", mar.nombre);
                    cmd.Parameters.AddWithValue("@estado", mar.estado);
                    con.Open();
                    cmd.ExecuteNonQuery();
                    mensaje = "Se registro la marca existosamente";
                }
                catch (SqlException ex)
                {
                    mensaje = ex.Message;

                }
                finally
                {
                    con.Close();
                }

            }
            return mensaje;
        }

        string EliminarMarca(string codigo)
        {
            string mensaje = "";
            using (SqlConnection con = new SqlConnection(cadena))
            {
                try
                {
                    SqlCommand cmd = new SqlCommand("sp_eliminar_marca", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@cod", codigo);
                    con.Open();
                    cmd.ExecuteNonQuery();
                    mensaje = "Se elimino la marca existosamente";
                }
                catch (SqlException ex)
                {
                    mensaje = ex.Message;
                }
                finally
                {
                    con.Close();
                }
            }
            return mensaje;
        }

        public ActionResult Listado()
        {
            IEnumerable<Marca> lista = ListarMarcas();
            return View(lista);
        }

        public ActionResult Registrar()
        {
            return View(new Marca());
        }

        [HttpPost]
        public ActionResult Registrar(Marca mar)
        {
            TempData["mensaje"] = RegistrarMarca(mar);
            return RedirectToAction("Listado");
        }

        public ActionResult Editar(string codigo = "")
        {
            Marca m = BuscarMarca(codigo);
            return View(m);
        }

        [HttpPost]
        public ActionResult Editar(Marca mar)
        {
            TempData["mensaje"] = EditarMarca(mar);
            return RedirectToAction("Listado");
        }

        public ActionResult Detalle(string codigo = "")
        {
            Marca mar = BuscarMarca(codigo);
            return View(mar);
        }

        public ActionResult Eliminar(string codigo = "")
        {
            TempData["mensaje"] = EliminarMarca(codigo);
            return RedirectToAction("Listado");
        }

        public void ReporteMarcas()
        {
            try
            {
                IEnumerable<Marca> listaMarcas = new List<Marca>();
                listaMarcas = ListarMarcas();

                ReportDocument rd = new ReportDocument();
                rd.Load(Path.Combine(Server.MapPath("~/Reportes"), "ReporteMarcas.rpt"));
                rd.SetDataSource(listaMarcas);

                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();


                rd.ExportToHttpResponse(ExportFormatType.PortableDocFormat, System.Web.HttpContext.Current.Response, false, "marcas");

            }
            catch (Exception ex)
            {
                Response.Write(ex.ToString());
            }
        }
    }
}

Mundo_Tecnologico/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mundo_Tecnologico.Models;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;

using CrystalDecisions.CrystalReports.Engine;
using System.IO;
using CrystalDecisions.Shared;

namespace Mundo_Tecnologico.Controllers
{
    public class UsuariosController : Controller
    {

        string cadena = ConfigurationManager.ConnectionStrings["con"].ConnectionString;

        IEnumerable<Usuario> ListarUsuarios()
        {
            List<Usuario> lista = new List<Usuario>();

            using (SqlConnection con = new SqlConnection(cadena))
            {
                SqlCommand cmd = new SqlCommand("sp_listar_usuarios", con);
                cmd.CommandType = CommandType.StoredProcedure;
                con.Open();

                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    Usuario reg = new Usuario()
                    {
                        codigo = dr.GetString(0),
                        nombre = dr.GetString(1),
                        apellidos = dr.GetString(2),
                        documento = dr.GetString(3),
                        celular = dr.GetString(4),
                        correo = dr.GetString(5),
                        estado = dr.GetByte(6),
                        tipoUsuario = dr.GetString(7),
                    };

                    lista.Add(reg);
                }
                dr.Close(); con.Close();
            }

            return lista;
        }

        IEnumerable<Usuario> ListarUsuariosEstado(int estado)
        {
            return ListarUsuarios().Where(u => u.estado == estado);
        }

        Usuario Buscar(string codigo)
        {
            if (codigo != null)
            {
                return ListarUsuarios().Where(u => u.codigo == codigo).FirstOrDefault();
            }
            else
            {
                return null;
            }
        }

        Usuario ValidarAcceso(string correo, string clave)
        {
            Usuario reg = null;

            using (SqlConnection con = new SqlConnection(cadena))
            {
                SqlCommand cmd = new SqlCommand("sp_validar_acceso", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@correo", correo);
                cmd.Parameters.AddWithValue("@clave", Usuario.GetSHA256(clave));
                con.Open();

                SqlDataReader dr = cmd.ExecuteReader();
                if (dr.Read())
                {
                    reg = new Usuario()
                    {
                        codigo = dr.GetString(0),
                        nombre = dr.GetString(1),
                        apellidos = dr.GetString(2),
                        correo = dr.GetString(3),
                        estado = dr.GetByte(4),
                        tipoUsuario = dr.GetString(5)
                    };

                }
                dr.Close(); con.Close();
            }

            return reg;
        }

        void IniciarSesion(Usuario reg)
        {
            Session["usuario"] = reg;
            Session.Timeout = 30; // 30 minutos de inactividad
        }

        void CerrarSesion()
        {
            Session.Abandon();
        }

        string RegistrarUsuario(Usuario reg, int tipoRegistro)
        {
            string mensaje = "";

            using (SqlConnection con = new SqlConnection(cadena))
            {
                try
                {
                    SqlCommand cmd = new SqlCommand("sp_registrar_usuario", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@nom", reg.nombre);
                    cmd.Parameters.AddWithValue("@ape", reg.apellidos);
                    cmd.Parameters.AddWithValue("@correo", reg.correo);
                    cmd.Parameters.AddWithValue("@documento", reg.documento);
                    cmd.Parameters.AddWithValue("@celular", reg.celular);
                    cmd.Parameters.AddWithValue("@clave", Usuario.GetSHA256(reg.clave));
                    
                    if(tipoRegistro == 1)
                    {
                        cmd.Parameters.AddWithValue("@cod_tip_usu", reg.codigoTipoUsuario);
                        cmd.Parameters.AddWithValue("@estado", reg.estado);
                    } else
                    {
                        cmd.Parameters.AddWithValue("@cod_tip_usu", "TPU0002");
                        cmd.Parameters.AddWithValue("@estado", 1);
                    }
                    

                    con.Open();
                    int i = cmd.ExecuteNonQuery();
                    mensaje = "Usuario " + reg.codigo + " registrado correctamente";
                }
                catch (Exception ex)
                {
                    mensaje = ex.Message;
                }
                finally
                {
                    con.Close();
                }
            }
            return mensaje;
        }

        string EditarUsuario(Usuario reg)
        {
            string mensaje = "";
            using (SqlConnection con = new SqlConnection(cadena))
            {
                try
                {
                    SqlCommand cmd = new SqlCommand("sp_editar_usuario", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@cod", reg.codigo);
                    cmd.Parameters.AddWithValue("@nom", reg.nombre);
                    cmd.Parameters.AddWithValue("@ape", reg.apellidos);
                    cmd.Parameters.AddWithValue("@doc", reg.documento);
                    cmd.Parameters.AddWithValue("@cel", reg.celular);
                    cmd.Parameters.AddWithValue("@corre", reg.correo);
                    cmd.Parameters.AddWithValue("@esta", reg.estado);
                    cmd.Parameters.AddWithValue("@cod_tip_usu", reg.codigoTipoUsuario);

                    con.Open();
                    int i = cmd.ExecuteNonQuery();
                    mensaje = "Usuario " + reg.codigo + " editado correctamente";
                }
                catch (Exception ex)
                {
                    mensaje = ex.Message;
                }
                finally
                {
                    con.Close();
                }

            }

            return mensaje;
        }

        string RestablecerClave(string codigo, string clave)
        {
            string mensaje = "";
            using (SqlConnection con = new SqlConnection(cadena))
            {
                try
                {
                    SqlCommand cmd = new SqlCommand("sp_restablecer_clave", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@cod", codigo);
                    cmd.Parameters.AddWithValue("@nuevaClave", Usuario.GetSHA256(clave));

                    con.Open();
                    int i = cmd.ExecuteNonQuery();
                    mensaje = "Clave restablecida correctamente";
                }
                catch (Exception ex)
                {
                    mensaje = ex.Message;
                }
                finally
                {
                    con.Close();
                }

            }

            return mensaje;
        }

        string EliminarUsuario(string codigo)
        {
            string mensaje = "";

            using (SqlConnection con = new SqlConnection(cadena))
            {
                try
                {
                    SqlCommand cmd = new SqlCommand("sp_eliminar_usuario", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@cod", codigo);

                    con.Open();
                    int i = cmd.ExecuteNonQuery();
                    mensaje = "Usuario " + codigo + " eliminado correctamente";

                }
                catch (Exception ex)
                {
                    mensaje = ex.Message;
                }
                finally
                {
                    con.Close();
                }

            }

            return mensaje;
        }

        public ActionResult Listado()
        {
            IEnumerable<Usuario> lista = ListarUsuarios();
            return View(lista);
        }

        public ActionResult Registrar()
        {
            return View(new Usuario());
        }

        [HttpPost]
        public ActionResult Registrar(Usuario reg)
        {
            TempData["mensaje"] = RegistrarUsuario(reg, 1);
            return RedirectToAction("Listado");
        }
        
        public ActionResult Editar(string codigo = null)
        {
            Usuario reg = Buscar(codigo);
            return View(reg);
        }

        [HttpPost]
        public ActionResult Editar(Usuario reg)
        {
            TempData["mensaje"] = EditarUsuario(reg);
            return RedirectToAction("Listado");
        }

        public ActionResult RegistroPersonal()
        {
            return View(new Usuario());
        }

        [HttpPost]
        public ActionResult RegistroPersonal(Usuario reg)
        {
            TempData["mensaje"] = RegistrarUsuario(reg, 2);
            return View();
        }


        public ActionResult Detalle(string codigo = "")
        {
            Usuario reg = Buscar(codigo);
            return View(reg);
        }

        public ActionResult Restablecer(string codigo = "")
        {
            ViewBag.codigo = codigo;
            return View();
        }

        [HttpPost]
        public ActionResult Restablecer(string codigo, string clave)
        {
            TempData["mensaje"] = RestablecerClave(codigo, clave);
            return RedirectToAction("Listado");
        }

        

Mundo_Tecnologico/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Mundo_Tecnologico.Models
@{
    if (Session["carrito"] == null)
    {
        Session["carrito"] = new List<Item>();
    }
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/Content/bootstrap.css">

    <!-- DataTables -->
    <link rel="stylesheet" href="~/Content/css/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/Content/css/responsive.bootstrap4.css">
    <link rel="stylesheet" href="~/Content/css/buttons.bootstrap4.min.css">

    <!-- Fuente -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Electrolize&display=swap" rel="stylesheet">

    <!-- CSS -->
    <link rel="stylesheet" href="~/Content/css/login.css">

    <style>
        body {
            font-family: 'Electrolize', sans-serif;
            background-image: url(@Url.Content("~/Img/fondo.jpg"));
            background-position: center center;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
        }
    </style>

</head>
<body>

    <div>
        @RenderBody()
    </div>
    <br />

    <!-- Font Awesome-->
    <script src="https://kit.fontawesome.com/7eb0bd06bd.js" crossorigin="anonymous"></script>

    <!-- JQuery -->
    <script src="~/Scripts/jquery.js"></script>

    <!-- Bootstrap -->
    <script src="~/Scripts/bootstrap.bundle.js"></script>

    <!-- DataTables  & Plugins -->
    <script src="~/Scripts/jquery.dataTables.js"></script>
    <script src="~/Scripts/dataTables.bootstrap4.js"></script>
    <script src="~/Scripts/dataTables.responsive.js"></script>
    <script src="~/Scripts/responsive.bootstrap4.js"></script>

    <!-- jquery-validation -->
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/additional-methods.js"></script>

    <!-- Swee Alert -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- JS -->
    <script src="~/Scripts/general.js"></script>
</body>
</html>

Mundo_Tecnologico/Views/Shared/_LayoutPrincipal.cshtml
<!DOCTYPE html>
@using Mundo_Tecnologico.Models
@{
    Usuario reg = Session["usuario"] as Usuario;
    if (Session["carrito"] == null)
    {
        Session["carrito"] = new List<Item>();
    }
    List<Item> carrito = Session["carrito"] as List<Item>;
}
<html lang="es">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/Content/bootstrap.css">

    <!-- DataTables -->
    <link rel="stylesheet" href="~/Content/css/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/Content/css/responsive.bootstrap4.css">
    <link rel="stylesheet" href="~/Content/css/buttons.bootstrap4.min.css">

    <!-- Fuente -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Electrolize&display=swap" rel="stylesheet">

    <!-- CSS -->
    <link rel="stylesheet" href="~/Content/css/general.css">
</head>
<body>

    <div class="header">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Mundo Tecnológico</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home")">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Nosotros", "Home")">Nosotros</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Catalogo", "Ecommerce")">Catálogo</a>
                    </li>

                    @if (reg != null)
                    {
                        if (reg.tipoUsuario == "Administrador")
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Mantenimiento</a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="@Url.Action("Listado", "Productos")">Productos</a>
                                    <a class="dropdown-item" href="@Url.Action("Listado", "Usuarios")">Usuarios</a>
                                    <a class="dropdown-item"
                                       href="@Url.Action("Listado", "Categorias")">Categorías</a>
                                    <a class="dropdown-item" href="@Url.Action("Listado", "Marcas")">Marcas</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("ListadoVentas", "Ecommerce")">Ventas</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Reportes</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="@Url.Action("ReporteProductos", "Productos")">Productos</a>
                                    <a class="dropdown-item" href="@Url.Action("ReporteVentas", "Ecommerce")">Ventas</a>
                                    <a class="dropdown-item" href="@Url.Action("ReporteUsuarios", "Usuarios")">Usuarios</a>
                                    <a class="dropdown-item" target="_blank" href="@Url.Action("ReporteCategorias", "Categorias")">Categorías</a>
                                    <a class="dropdown-item" target="_blank" href="@Url.Action("ReporteMarcas", "Marcas")">Marcas</a>
                                </div>
                            </li>
                        }
                    }
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Carrito", "Ecommerce")"><i class="fas fa-cart-plus"></i> (@(carrito.Count)) Carrito</a>
                    </li>
                    @if (Session["usuario"] != null)
                    {
                        <li class="nav-item dropdown mr-auto">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-user"></i> @(reg.nombre + " " + reg.apellidos)
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @Html.ActionLink("Cerrar Sesión", "Cerrar", "Usuarios", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Mis Compras", "MisCompras", "Ecommerce", null, new { @class = "dropdown-item" })
                            </div>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Login", "Home")"><i class="fas fa-user"></i> Iniciar Sesión</a>
                        </li>
                    }

                </ul>
            </div>
        </nav>

    </div>

    <div class="contenido">
        @RenderBody()
    </div>

    <footer class="text-center bg-dark">
        <div class="">
            <!-- Facebook -->
            <a class="btn btn-link btn-floating btn-lg m-1 text-light " href="#!" role="button"
               data-mdb-ripple-color="light"><i class="fab fa-facebook-f"></i></a>

            <!-- Twitter -->
            <a class="btn btn-link btn-floating btn-lg m-1 text-light " href="#!" role="button"
               data-mdb-ripple-color="dark"><i class="fab fa-twitter"></i></a>

            <!-- Instagram -->
            <a class="btn btn-link btn-floating btn-lg m-1 text-light " href="#!" role="button"
               data-mdb-ripple-color="dark"><i class="fab fa-instagram"></i></a>
        </div>
        <!-- Copyright -->
        <div class="text-center text-light">
            © 2021
            <a class="text-light" href="@Url.Action("Index", "Home")">Mundo Tecnológico</a>
        </div>
        <!-- Copyright -->
    </footer>

    <!-- Font Awesome-->
    <script src="https://kit.fontawesome.com/7eb0bd06bd.js" crossorigin="anonymous"></script>

    <!-- JQuery -->
    <script src="~/Scripts/jquery.js"></script>

    <!-- Bootstrap -->
    <script src="~/Scripts/bootstrap.bundle.js"></script>

    <!-- DataTables  & Plugins -->
    <script src="~/Scripts/jquery.dataTables.js"></script>
    <script src="~/Scripts/dataTables.bootstrap4.js"></script>
    <script src="~/Scripts/dataTables.responsive.js"></script>
    <script src="~/Scripts/responsive.bootstrap4.js"></script>

    <!-- jquery-validation -->
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/additional-methods.js"></script>

    <!-- Swee Alert -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- JS -->
    <script src="~/Scripts/general.js"></script>

    <script>
        function Mostrar() {
            $("#frmReporte").attr("src", "https://app.powerbi.com/view?r=eyJrIjoiZjI3Zjc0MjQtNGFjNy00ODBjLWI0NmQtNWViYzhiYzM2Y2Q1IiwidCI6ImUxNGZjMDZjLTQzZWQtNDE2MC1hMDg0LWU3NjcxYjcwYjE3OSIsImMiOjR9").load();
        }
    </script>

</body>
</html>