Mundo_Tecnologico/Controllers/EcommerceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mundo_Tecnologico.Models;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;
using CrystalDecisions.Shared;

namespace Mundo_Tecnologico.Controllers
{
    public class EcommerceController : Controller
    {
        string cadena = ConfigurationManager.ConnectionStrings["con"].ConnectionString;

        IEnumerable<Producto> FiltrarProductos(string criterio, string filtro)
        {
            List<Producto> lista = new List<Producto>();

            using (SqlConnection con = new SqlConnection(cadena))
            {
                SqlCommand cmd = new SqlCommand("sp_filtrar_productos", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@criterio", criterio);
                cmd.Parameters.AddWithValue("@filtro", filtro);
                con.Open();

                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    Producto reg = new Producto()
                    {
                        codigo = dr.GetString(0),
                        foto = dr.GetString(1),
                        nombre = dr.GetString(2),
                        descripcion = dr.GetString(3),
                        precio = dr.GetDecimal(4),
                        stock = dr.GetInt32(5),
                    };

                    lista.Add(reg);
                }

                dr.Close();
                con.Close();

            }

            return lista;

        }

        Producto Buscar(string codigo)
        {
            if (codigo != null)
            {
                return FiltrarProductos("nombre", "").Where(p => p.codigo == codigo).FirstOrDefault();
            }
            else
            {
                return null;
            }

        }

        Usuario BuscarUsuario(string codigo)
        {

            Usuario reg = null;

            using (SqlConnection con = new SqlConnection(cadena))
            {
                SqlCommand cmd = new SqlCommand("SP_USUARIO_VENTA", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@codigo", codigo);
                con.Open();

                SqlDataReader dr = cmd.ExecuteReader();
                if (dr.Read())
                {
                    reg = new Usuario()
                    {
                        documento = dr.GetString(0),
                        celular = dr.GetString(1)
                    };

                }

                dr.Close();
                con.Close();
            }

            return reg;
        }

        IEnumerable<Distrito> ListarDistritos()
        {
            List<Distrito> lista = new List<Distrito>();

            using (SqlConnection con = new SqlConnection(cadena))
            {
                SqlCommand cmd = new SqlCommand("sp_listar_distritos", con);
                cmd.CommandType = CommandType.StoredProcedure;
                con.Open();

                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    Distrito reg = new Distrito();
                    reg.codigo = dr.GetString(0);
                    reg.nombre = dr.GetString(1);

                    lista.Add(reg);
                }

                dr.Close();
                con.Close();
            }

            return lista;
        }

        IEnumerable<Venta> ListarVentas()
        {
            List<Venta> lista = new List<Venta>();

            using (SqlConnection con = new SqlConnection(cadena))
            {
                SqlCommand cmd = new SqlCommand("SP_LISTAR_VENTAS", con);
                cmd.CommandType = CommandType.StoredProcedure;
                con.Open();

                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    Venta reg = new Venta()
                    {
                        codigo = dr.GetString(0),
                        fecha = dr.GetDateTime(1),
                        distrito = dr.GetString(2),
                        direccion = dr.GetString(3),
                        referencia = dr.GetString(4),
                        total = dr.GetDecimal(5),
                        estado = dr.GetByte(6),
                        usuario = dr.GetString(7),
                        codigoUsuario = dr.GetString(8),
                        celular = dr.GetString(9),
                        documento = dr.GetString(10)
                    };

                    lista.Add(reg);
                }
                dr.Close(); con.Close();
            }

            return lista;
        }

        IEnumerable<Venta> ListarVentasFechas(DateTime f1, DateTime f2)
        {
            List<Venta> lista = new List<Venta>();

            using (SqlConnection con = new SqlConnection(cadena))
            {
                SqlCommand cmd = new SqlCommand("SP_LISTAR_VENTAS_FECHAS", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("f1", f1);
                cmd.Parameters.AddWithValue("f2", f2);
                con.Open();

                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    Venta reg = new Venta()
                    {
                        codigo = dr.GetString(0),
                        fecha = dr.GetDateTime(1),
                        direccion = dr.GetString(2),
                        total = dr.GetDecimal(3),
                        estado = dr.GetByte(4),
                        usuario = dr.GetString(5),
                        distrito = dr.GetString(6),
                        celular = dr.GetString(7),
                        documento = dr.GetString(8)
                    };

                    lista.Add(reg);
                }
                dr.Close(); con.Close();
            }

            return lista;
        }

        IEnumerable<Venta> Ventas()
        {
            return ListarVentas().Where(v => v.estado == 1 || v.estado == 2);
        }

        IEnumerable<Item> DetallarVenta(string codigo)
        {
            List<Item> lista = new List<Item>();

            using (SqlConnection con = new SqlConnection(cadena))
            {
                SqlCommand cmd = new SqlCommand("SP_LISTAR_DETALLE_VENTA", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@codigo", codigo);
                con.Open();

                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    Item reg = new Item()
                    {
                        nombre = dr.GetString(0),
                        cantidad = dr.GetInt32(1),
                        precio = dr.GetDecimal(2),
                        codigo = dr.GetString(3)
                    };

                    lista.Add(reg);
                }
                dr.Close(); con.Close();
            }

            return lista;
        }

        IEnumerable<Venta> VentaUsuario(string codigoUsuario)
        {
            return ListarVentas().Where(v => v.codigoUsuario == codigoUsuario).ToList();
        }

        string EditarVenta(string codigo, int estado)
        {
            string mensaje = "";

            using (SqlConnection con = new SqlConnection(cadena))
            {
                try
                {
                    SqlCommand cmd = new SqlCommand("SP_EDITAR_VENTA", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@codigo", codigo);
                    cmd.Parameters.AddWithValue("@estado", estado);

                    con.Open();
                    int i = cmd.ExecuteNonQuery();
                    mensaje = "Venta " + codigo + " editada correctamente";

                }
                catch (Exception ex)
                {
                    mensaje = ex.Message;
                }
                finally
                {
                    con.Close();
                }

            }

            return mensaje;
        }

        string AgregarCarrito(string codigo, Int16 stock, int cantidad)
        {

            Producto reg = Buscar(codigo);
            Item it = new Item()
            {
                codigo = reg.codigo,
                nombre = reg.nombre,
                precio = reg.precio,
                stock = reg.stock,
                cantidad = cantidad
            };

            List<Item> temporal = (List<Item>)Session["carrito"];
            bool bandera = true;

            foreach (var item in temporal)
            {
                if (item.codigo == reg.codigo)
                {
                    if ((item.cantidad += cantidad) > reg.stock)
                        item.cantidad = reg.stock;
                    else
                        item.cantidad += cantidad;

                    bandera = false;
                    break;
                }
            }

            if (bandera)
                temporal.Add(it);

            return "Producto agregado al carrito";
        }

        void EditarCarrito(string codigo, int cantidad)
        {
            List<Item> temporal = Session["carrito"] as List<Item>;

            foreach (var item in temporal)
            {
                if (item.codigo == codigo)
                {
                    item.cantidad = cantidad;
                    break;
                }
            }
        }

        void EliminarCarrito(string codigo)
        {
            List<Item> temporal = Session["carrito"] as List<Item>;
            temporal.Remove(temporal.Where(i => i.codigo == codigo).FirstOrDefault());
        }

Mundo_Tecnologico/Views/Ecommerce/Aviso.cshtml
@using Mundo_Tecnologico.Models
@{
    ViewBag.Title = "Aviso | Mundo Tecnológico";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<div class="container text-center contenedor_mantenimiento">
    <h1>Operación Exitosa</h1>
    <h2>@ViewBag.mensaje</h2>
    <h3>Muchas gracias por tu compra, @((Session["usuario"] as Usuario).nombre)</h3>
    <h3>Nos comunicaremos contigo muy pronto</h3>
</div>

Mundo_Tecnologico/Views/Ecommerce/Carrito.cshtml
@model IEnumerable<Mundo_Tecnologico.Models.Item>

@using Mundo_Tecnologico.Models
@{
    ViewBag.Title = "Carrito | Mundo Tecnológico";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<div class="container-fluid contenedor_mantenimiento">
    <div class="row">
        <div class="col-md-10 m-auto">
            <table class="table table-sm table-hover table-responsive table-striped" style="width:100%">
                <thead>
                    <tr>
                        <th style="width: 10%">CÓDIGO</th>
                        <th style="width: 50%">NOMBRE</th>
                        <th style="width: 14%">P.U</th>
                        <th style="width: 16%">CANTIDAD</th>
                        <th style="width: 13%">SUBTOTAL</th>
                        <th style="width: 7%">Operaciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td id="codigo">@item.codigo</td>
                            <td>@item.nombre</td>
                            <td>S/. @item.precio.ToString("F")</td>
                            <td>
                                <div class="input-group number-spinner">
                                    <span class="input-group-btn">
                                        <button type="button" class="btn btn-default" data-dir="dwn"><span>-</span></button>
                                    </span>
                                    <input name="cantidad" id="cantidad" type="number" max="@item.stock" min="1" readonly class="form-control text-center" value="@item.cantidad">
                                    <span class="input-group-btn">
                                        <button type="button" class="btn btn-default" data-dir="up"><span>+</span></button>
                                    </span>
                                </div>
                            </td>
                            <td>S/. @item.monto.ToString("F")</td>
                            <td class="text-center">
                                <a href="#" class="editarCarrito"><i class="fas fa-sync"></i></a>
                                <a href="@Url.Action("Eliminar", "Ecommerce", new { codigo = item.codigo})" onclick="return ConfirmarDeleteCarrito(event, '@item.codigo')" style="color: red">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 m-auto">
            <div class="card">
                <div class="card-header text-center">
                    <h3>Procesar Compra</h3>
                </div>
                <form action="Procesar" method="get" id="formularioVenta">
                    <div class="card-body">
                        <div class="row">
                            <label for="total" class="col-sm-4 col-form-label">Total (S/.)</label>
                            <div class="col-sm-8 form-group">
                                <input type="text" readonly class="form-control" id="total" name="total" value="@Model.Sum(c => c.monto)">
                            </div>
                        </div>
                        <div class="row">
                            <label for="codigoDistrito" class="col-sm-4 col-form-label">Distrito</label>
                            <div class="col-sm-8 form-group">
                                <select class="custom-select" name="codigoDistrito">
                                    <option selected disabled>Seleccione</option>
                                    @foreach (var item in (IEnumerable<Distrito>)ViewBag.distritos)
                                    {
                                        <option value="@item.codigo">@item.nombre</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <label for="direccion" class="col-sm-4 col-form-label">Dirección de entrega</label>
                            <div class="col-sm-8 form-group">
                                <input type="text" class="form-control" id="direccion" name="direccion" placeholder="Ingrese la dirección para entrega del pedido">
                            </div>
                        </div>

                        <div class="row">
                            <label for="referencia" class="col-sm-4 col-form-label">Referencia</label>
                            <div class="col-sm-8 form-group">
                                <input type="text" class="form-control" id="referencia" name="referencia" placeholder="Ingrese una referencia para la entrega">
                            </div>
                        </div>
                    </div>
                    <div class="card-footer text-center">
                        @if (Model.Count() > 0)
                        {
                            <button type="submit" class="btn btn-success mr-5">Procesar Compra</button>
                        }
                        <a href="@Url.Action("Catalogo", "Ecommerce")" class="btn btn-secondary">Seguir comprando</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Mundo_Tecnologico/Views/Ecommerce/Catalogo.cshtml
@model IEnumerable<Mundo_Tecnologico.Models.Producto>

@{
    ViewBag.Title = "Catalogo | Mundo Tecnológico";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<form class="container busqueda">
    <div class="form-group  pr-3 pl-3 row d-flex justify-content-around flex-wrap">
        <label class="col-form-label mt-1">Filtrar productos por: </label>
        <select class="custom-select col-sm-3 mt-1" name="criterio">
            <option value="Nombre" @(ViewBag.criterio == "Nombre" ? "selected" : "")>Nombre</option>
            <option value="Categoria" @(ViewBag.criterio == "Categoria" ? "selected" : "")>Categoria</option>
            <option value="Marca" @(ViewBag.criterio == "Marca" ? "selected" : "")>Marca</option>
        </select>
        <input class="form-control col-sm-3 mt-1" name="filtro" placeholder="Ingrese el valor a filtrar" value="@ViewBag.filtro" />
        <button type="submit" class="btn btn-secondary col-sm-3 mt-1">Filtrar</button>
    </div>
</form>

<div class="container">

    <table class="w-100">

        <tr class="text-center w-100 d-flex justify-content-center flex-wrap">
            @foreach (var item in Model)
            {
                <td width="30%" class="detalle-catalogo m-2">
                    <table class="w-100 producto">
                        <tr class="cabecera-catalogo"><td>@item.nombre.ToUpper()</td></tr>
                        <tr><td><img src="@Url.Content(item.foto)" class="catalogo" /></td></tr>
                        <tr><td>Precio Unitario: <strong>S/. @item.precio</strong></td></tr>
                        <tr><td>Stock: <strong>@item.stock unidades</strong></td></tr>
                        <tr><td>@Html.ActionLink("Ver Producto", "DetalleAgregar", "Ecommerce", new { codigo = item.codigo }, new { @class = "btn btn-primary" })</td></tr>
                        <tr><td><br /></td></tr>
                    </table>
                </td>
            }

        </tr>

    </table>
    @if (Model.Count() > 0) // Valida si hay resultados
    {
        <div class="text-center">



            <div>
                @Html.ActionLink("|<", "Catalogo", new { criterio = ViewBag.criterio, filtro = ViewBag.filtro, f = "inicio" }, new { @class = "btn btn-secondary" })
                @Html.ActionLink("<", "Catalogo", new { pagInicio = (int)ViewBag.pagInicio, criterio = ViewBag.criterio, filtro = ViewBag.filtro, f = "izquierda" }, new { @class = "btn btn-secondary" })
                @Html.Label("Página " + ((int)ViewBag.pagInicio + 1 ).ToString() + " de " + ((int)ViewBag.numPaginas).ToString(), null, new { @class = "btn btn-primary mt-2" })
                @Html.ActionLink(">", "Catalogo", new { pagInicio = (int)ViewBag.pagInicio, criterio = ViewBag.criterio, filtro = ViewBag.filtro, f = "derecha" }, new { @class = "btn btn-secondary" })
                @Html.ActionLink(">|", "Catalogo", new { criterio = ViewBag.criterio, filtro = ViewBag.filtro, f = "fin" }, new { @class = "btn btn-secondary" })
            </div>



        </div>
    }

    @if (Model.Count() == 0)
    {
        <div class="alert alert-danger text-center" role="alert">
            <strong> No hay productos que coincidan con la búsqueda </strong>
        </div>
    }

</div>            }

Mundo_Tecnologico/Views/Ecommerce/Detalle.cshtml
@model Mundo_Tecnologico.Models.Producto

@{
    ViewBag.Title = "Detalle del Producto | Mundo Tecnológico";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<!-- Default box -->
<div class="card card-solid col-md-9 detalle-producto">
    <div class="card-body">
        <div class="row d-flex flex-wrap">
            <div class="col-12 col-sm-5">
                <div class="col-12">
                    <img src="@Url.Content(Model.foto)" class="img-fluid m-auto" alt="Product Image">
                </div>
            </div>
            <div class="col-12 col-sm-7">
                <h3 class="my-3">@Model.nombre.ToUpper()</h3>
                <p>@Model.descripcion</p>

                <hr>

                <div class="bg-gray py-2 px-3 mt-4">
                    <h2 class="mb-0">
                        S/. @Model.precio
                    </h2>
                </div>

                <form action="@Url.Action("Detalle", "Ecommerce", new { codigo = Model.codigo})">
                    <div class="mt-4 row">

                        <div class="col-md-4 mt-1">
                            <div class="input-group number-spinner">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-default" data-dir="dwn"><span>-</span></button>
                                </span>
                                <input name="cantidad" type="number" min="1" readonly class="form-control text-center" value="1">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-default" data-dir="up"><span>+</span></button>
                                </span>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg btn-flat">
                            <i class="fas fa-cart-plus fa-lg mr-2"></i>
                            Añadir al Carrito
                        </button>

                    </div>
                </form>

            </div>
        </div>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

Mundo_Tecnologico/Views/Ecommerce/DetalleAgregar.cshtml
@model Mundo_Tecnologico.Models.Producto
@using Mundo_Tecnologico.Models
@{
    ViewBag.Title = "Detalle del Producto | Mundo Tecnológico";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<!-- Default box -->
<div class="card card-solid col-md-9 detalle-producto">
    <div class="card-body">

        @if (TempData["mensaje"] != null)
        {
            <div class="alert alert-info text-center" role="alert">
                <strong> @TempData["mensaje"] </strong>
            </div>
        }

        <div class="row d-flex flex-wrap">
            <div class="col-12 col-sm-5">
                <div class="col-12">
                    <img src="@Url.Content(Model.foto)" class="img-fluid m-auto" alt="Product Image">
                </div>
            </div>
            <div class="col-12 col-sm-7">

                <h3 class="my-3">@Model.nombre.ToUpper()</h3>
                <p>@Model.descripcion</p>

                <hr>

                <div class="bg-gray py-2 px-3 mt-4">
                    <h2 class="mb-0">
                        S/. @Model.precio
                    </h2>

                    <span> @Model.stock unidades disponibles</span>
                </div>

                <form action="@Url.Action("Agregar", "Ecommerce")" method="post">
                    <div class="mt-4 row">

                        @Html.Hidden("codigo", Model.codigo)
                        @Html.Hidden("stock", Model.stock)

                        <div class="col-md-4 mt-1">
                            <div class="input-group number-spinner">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-default" data-dir="dwn"><span>-</span></button>
                                </span>
                                <input name="cantidad" type="number" min="1" max="@Model.stock" readonly class="form-control text-center" value="1">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-default" data-dir="up"><span>+</span></button>
                                </span>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg btn-flat mr-2">
                            <i class="fas fa-cart-plus fa-lg mr-2"></i>
                            Añadir al Carrito
                        </button>
                        <a class="btn btn-secondary btn-lg btn-flat mr-2" href="@Url.Action("Catalogo", "Ecommerce")">Seguir comprando</a>
                    </div>
                </form>

            </div>
        </div>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

Mundo_Tecnologico/Views/Ecommerce/DetalleVenta.cshtml
@model IEnumerable<Mundo_Tecnologico.Models.Item>

@{
    ViewBag.Title = "Detalle Usuario | Mundo Tecnológico";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<div class="contenedor_mantenimiento col-md-6 m-auto">
    <div class="card card-primary">

        <div class="card-header text-center">
            <h2 class="">Detalle de la Venta - @ViewBag.codigo</h2>
        </div>

        <div class="card-body">
            <table class="table table-hover table-striped table-sm" style="width:100%">
                <thead>
                    <tr>
                        <th>PRODUCTO</th>
                        <th>CANTIDAD</th>
                        <th>MONTO</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.nombre</td>
                            <td>@item.cantidad</td>
                            <td>S/. @item.monto</td>
                        </tr>
                    }
                </tbody>
            </table>

            <div class="card-footer d-flex justify-content-center">
                <a href="@Url.Action("Editar", "Ecommerce", new { codigo = ViewBag.codigo, estado = 2 })" class="btn btn-success mr-5 col-sm-3"><i class="fas fa-shipping-fast"></i> Aprobar</a>
                <a href="@Url.Action("Editar", "Ecommerce", new { codigo = ViewBag.codigo, estado = 4 })" class="btn btn-danger mr-5 col-sm-3"><i class="fas fa-ban"></i> Rechazar</a>
                <a href="@Url.Action("ListadoVentas", "Ecommerce")" class="btn btn-secondary col-sm-3">Volver al Listado</a>
            </div>
        </div>
    </div>
</div>

Mundo_Tecnologico/Views/Ecommerce/ListadoVentas.cshtml
@model IEnumerable<Mundo_Tecnologico.Models.Venta>

@{
    ViewBag.Title = "Listado de Usuarios | Mundo Tecnológico";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<div class="contenedor_mantenimiento col-md-12 m-auto">
    <div class="card card-primary">

        <div class="card-header text-center">
            <h2 class="">Listado de Ventas Pendientes y Aprobadas</h2>
        </div>

        <div class="card-body">

            @if (TempData["mensaje"] != null)
            {
                <div class="alert alert-info" role="alert">
                    <b><span>@TempData["mensaje"]</span></b>
                </div>
            }

            <table id="dataTableVenta" class="table table-sm table-hover dt-responsive wrap" style="width:100%">
                <thead>
                    <tr>
                        <th style="width: 7%;">CÓDIGO</th>
                        <th style="width: 12%;">FECHA - HORA</th>
                        <th style="width: 7%;">TOTAL</th>
                        <th style="width: 15%;">DISTRITO</th>
                        <th style="width: 20%;">DIRECCION</th>
                        <th style="width: 20%;">REFERENCIA</th>
                        <th style="width: 15%;">USUARIO</th>
                        <th style="width: 5%;">CELULAR</th>
                        <th style="width: 5%;">DOCUMENTO</th>
                        <th style="width: 13%;">ESTADO</th>
                        <th style="width: 5%;">OPE.</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.codigo</td>
                            <td>@item.fecha.ToShortDateString() - @item.fecha.ToLongTimeString()</td>
                            <td>S/. @item.total</td>
                            <td>@item.distrito</td>
                            <td>@item.direccion</td>
                            <td>@item.referencia</td>
                            <td>@item.usuario</td>
                            <td>@item.celular</td>
                            <td>@item.documento</td>
                            @switch (item.estado)
                            {
                                case 1:
                                    <td>Pendiente</td>
                                    break;
                                case 2:
                                    <td>Aprobada</td>
                                    break;
                            }
                        <td class="text-center">

                            @if (item.estado == 1)
                            {
                                <a href="@Url.Action("DetalleVenta", "Ecommerce", new { codigo = item.codigo })" style="color: green"><i class="fas fa-info-circle"></i></a>
                            }

                            @if (item.estado == 2)
                            {
                                <a href="@Url.Action("Editar", "Ecommerce", new { codigo = item.codigo, estado = 3 })" style="color: blue"><i class="fas fa-people-carry"></i></a>
                            }
                        </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Mundo_Tecnologico/Views/Ecommerce/MisCompras.cshtml
@model IEnumerable<Mundo_Tecnologico.Models.Venta>

@{
    ViewBag.Title = "Listado de Usuarios | Mundo Tecnológico";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<div class="contenedor_mantenimiento col-md-12 m-auto">
    <div class="card card-primary">

        <div class="card-header text-center">
            <h2 class="">Mis Compras</h2>
        </div>

        <div class="card-body">

            <table id="dataTable" class="table table-sm table-hover dt-responsive wrap" style="width:100%">
                <thead>
                    <tr>
                        <th style="width: 10%;">CÓDIGO</th>
                        <th style="width: 10%;">FECHA - HORA</th>
                        <th style="width: 7%;">TOTAL</th>
                        <th style="width: 12%;">DISTRITO</th>
                        <th style="width: 25%;">DIRECCION</th>
                        <th style="width: 25%;">REFERENCIA</th>
                        <th style="width: 7%;">ESTADO</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.codigo</td>
                        <td>@item.fecha.ToShortDateString() - @item.fecha.ToLongTimeString()</td>
                        <td>S/. @item.total</td>
                        <td>@item.distrito</td>
                        <td>@item.direccion</td>
                        <td>@item.referencia</td>
                        @switch (item.estado)
                        {
                            case 1:
                                <td>Pendiente</td>
                                break;
                            case 2:
                                <td>Aprobada</td>
                                break;
                            case 3:
                                <td>Entregada</td>
                                break;
                            case 4:
                                <td>Rechazada</td>
                                break;
                        }
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>